{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "twenty-helm.fullname" . }}-tokens
  labels:
    {{- include "twenty-helm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.appSecret }}
  {{ .Values.secrets.appSecretKey | default "accessToken" }}: {{ .Values.secrets.appSecret | b64enc | quote }}
  {{- else }}
  {{ .Values.secrets.appSecretKey | default "accessToken" }}: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}